apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: capstoneacrmicrodeploy.azurecr.io/user-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_USER
          value: "sameer"
        - name: DB_PASSWORD
          value: "Sameer@141102"
        - name: DB_NAME
          value: "usersdb"
        - name: JWT_SECRET
          value: "secretjwt"
